
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_sqlite
                memory: true
    orm:
        default_entity_manager: default
        entity_managers:
            default:

                mappings:
                    BespokeSupportCreatedUpdatedDeletedBundle:
                        mapping: true
                        type: annotation
                        prefix: BespokeSupport\CreatedUpdatedDeletedBundle\Tests\TestEntities
                        dir: './Tests/TestEntities'
