services:

  bespokesupport.createdupdateddeleted.listener.created:
      class: BespokeSupport\CreatedUpdatedDeletedBundle\Service\CudCreatedListener
      public: true
      tags:
          - { name: doctrine.event_listener, event: prePersist }

  bespokesupport.createdupdateddeleted.listener.updated:
      class: BespokeSupport\CreatedUpdatedDeletedBundle\Service\CudUpdatedListener
      public: true
      tags:
          - { name: doctrine.event_listener, event: preUpdate }

  bespokesupport.createdupdateddeleted.listener.deleted:
      class: BespokeSupport\CreatedUpdatedDeletedBundle\Service\CudDeletedListener
      public: true
      tags:
          - { name: doctrine.event_listener, event: onFlush }
